import { MagicByte } from "./magic-byte";

export class MagicBytesData {
  magic_bytes_data: MagicByte[] = [
  {ascii: "....",
  description: "RedHat Package Manager (RPM) package",
  file_extension: "rpm",
  hex: "ed ab ee db",
  offset: "0"},
  {ascii: "SP01",
  description: "Amazon Kindle Update Package",
  file_extension: "bin",
  hex: "53 50 30 31",
  offset: "0"},
  {ascii: ".",
  description: "WindowsProgram Information File",
  file_extension: "PIF",
  hex: "00 nn",
  offset: "0"},
  {ascii: ".",
  description: "MacStuffit Self-Extracting Archive",
  file_extension: "SEA",
  hex: "00 nn",
  offset: "0"},
  {ascii: ".",
  description: "IRISOCR data file",
  file_extension: "YTR",
  hex: "00 nn",
  offset: "0"},
  {ascii: ".",
  description: "IBM Storyboard bitmap file",
  file_extension: "PIC",
  hex: "00 nn",
  offset: "0"},
  {ascii: "........ ........ ........",
  description: "PalmPilot Database/Document File",
  file_extension: "PDB",
  hex: "00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00",
  offset: "11"},
  {ascii: "...",
  description: "Palm Desktop Calendar Archive",
  file_extension: "DBA",
  hex: "BE BA FE CA",
  offset: "0"},
  {ascii: "..BD",
  description: "Palm Desktop To Do Archive",
  file_extension: "DBA",
  hex: "00 01 42 44",
  offset: "0"},
  {ascii: "..DT",
  description: "Palm Desktop Calendar Archive",
  file_extension: "TDA",
  hex: "00 01 44 54",
  offset: "0"},
  {ascii: "...",
  description: "Palm Desktop Data File (Access format)",
  file_extension: "",
  hex: "00 01 00 00",
  offset: "0"},
  {ascii: "....",
  description: "Computer icon encoded inICO file format",
  file_extension: "ico",
  hex: "00 00 01 00",
  offset: "0"},
  {ascii: "ftyp 3g",
  description: "3rd Generation Partnership Project3GPP",
  file_extension: "3gp",
  hex: "66 74 79 70 33 67",
  offset: "4"},
  {ascii: "ftyp 3g",
  description: "3GPP2 multimedia files",
  file_extension: "3g2",
  hex: "66 74 79 70 33 67",
  offset: "4"},
  {ascii: "..",
  description: "compressed file (often tar zip)",
  file_extension: "z",
  hex: "1F 9D",
  offset: "0"},
  {ascii: "..",
  description: "usingLempel-Ziv-Welch algorithm",
  file_extension: "tar.z",
  hex: "1F 9D",
  offset: "0"},
  {ascii: "..",
  description: "Compressed file (often tar zip)",
  file_extension: "z",
  hex: "1F A0",
  offset: "0"},
  {ascii: "..",
  description: "usingLZH algorithm",
  file_extension: "tar.z",
  hex: "1F A0",
  offset: "0"},
  {ascii: "BACKMIKE DISK",
  description: "File ortape containing abackup done withAmiBack on an Amiga. It typically is paired with an index file (idx) with the table of contents.",
  file_extension: "bac",
  hex: "42 41 43 4B 4D 49 4B 45 44 49 53 4B",
  offset: "0"},
  {ascii: "BZh",
  description: "Compressed file usingBzip2 algorithm",
  file_extension: "bz2",
  hex: "42 5A 68",
  offset: "0"},
  {ascii: "GIF87aGIF89a",
  description: "Image file encoded in theGraphics Interchange Format (GIF)",
  file_extension: "gif",
  hex: "47 49 46 38 37 61 47 49 46 38 39 61",
  offset: "0"},
  {ascii: "II*.MM.*",
  description: "Tagged Image File Format (little endian format)",
  file_extension: "tif",
  hex: "49 49 2A 00",
  offset: "0"},
  {ascii: "II*.MM.*",
  description: "Tagged Image File Format (little endian format)",
  file_extension: "tiff",
  hex: "49 49 2A 00",
  offset: "0"},
  {ascii: "II*.MM.*",
  description: "Tagged Image File Format (big endian format)",
  file_extension: "tif",
  hex: "4D 4D 00 2A",
  offset: "0"},
  {ascii: "II*.MM.*",
  description: "Tagged Image File Format (big endian format)",
  file_extension: "tiff",
  hex: "4D 4D 00 2A",
  offset: "0"},
  {ascii: "II*..... CR",
  description: "Canon's RAW format is based on the TIFF file format",
  file_extension: "cr2",
  hex: "49 49 2A 00 10 00 00 00 43 52",
  offset: "0"},
  {ascii: "II*..... CR",
  description: "Canon RAW Format Version 2",
  file_extension: "cr2",
  hex: "49 49 2A 00 10 00 00 00 43 52",
  offset: "0"},
  {ascii: ".*_.",
  description: "KodakCineon image",
  file_extension: "cin",
  hex: "80 2A 5F D7",
  offset: "0"},
  {ascii: "RNC.",
  description: "Compressed file usingRob Northen Compression (version 1 and 2) algorithm",
  file_extension: "",
  hex: "52 4E 43 01 52 4E 43 02",
  offset: "0"},
  {ascii: "SDPXXPDS",
  description: "SMPTEDPX image (big endian format)",
  file_extension: "dpx",
  hex: "53 44 50 58",
  offset: "0"},
  {ascii: "SDPXXPDS",
  description: "SMPTEDPX image (little endian format)",
  file_extension: "dpx",
  hex: "58 50 44 53",
  offset: "0"},
  {ascii: "v/1.",
  description: "OpenEXR image",
  file_extension: "exr",
  hex: "76 2F 31 01",
  offset: "0"},
  {ascii: "BPGû",
  description: "Better Portable Graphics format",
  file_extension: "bpg",
  hex: "42 50 47 FB",
  offset: "0"},
  {ascii: "ÿØÿÛ",
  description: "JPEG raw or in theJFIF orExif file format",
  file_extension: "jpg",
  hex: "FF D8 FF DB",
  offset: "0"},
  {ascii: "ÿØÿÛ",
  description: "JPEG raw or in theJFIF orExif file format",
  file_extension: "jpeg",
  hex: "FF D8 FF DB",
  offset: "0"},
  {ascii: "ÿØÿà ..J F IF..",
  description: "JPEG raw or in theJFIF orExif file format",
  file_extension: "jpg",
  hex: "FF D8 FF E0 00 10 4A 46 49 46 00 01",
  offset: "0"},
  {ascii: "ÿØÿà ..J F IF..",
  description: "JPEG raw or in theJFIF orExif file format",
  file_extension: "jpeg",
  hex: "FF D8 FF E0 00 10 4A 46 49 46 00 01",
  offset: "0"},
  {ascii: "ÿØÿá ..E x if..",
  description: "JPEG raw or in theJFIF orExif file format",
  file_extension: "jpg",
  hex: "FF D8 FF E1 nn nn 45 78 69 66 00 00",
  offset: "0"},
  {ascii: "ÿØÿá ..E x if..",
  description: "JPEG raw or in theJFIF orExif file format",
  file_extension: "jpeg",
  hex: "FF D8 FF E1 nn nn 45 78 69 66 00 00",
  offset: "0"},
  {ascii: "FORM.... ILBM",
  description: "IFFInterleaved Bitmap Image",
  file_extension: "ilbm",
  hex: "46 4F 52 4D nn nn nn nn 49 4C 42 4D",
  offset: "any"},
  {ascii: "FORM.... ILBM",
  description: "IFFInterleaved Bitmap Image",
  file_extension: "lbm",
  hex: "46 4F 52 4D nn nn nn nn 49 4C 42 4D",
  offset: "any"},
  {ascii: "FORM.... ILBM",
  description: "IFFInterleaved Bitmap Image",
  file_extension: "ibm",
  hex: "46 4F 52 4D nn nn nn nn 49 4C 42 4D",
  offset: "any"},
  {ascii: "FORM.... ILBM",
  description: "IFFInterleaved Bitmap Image",
  file_extension: "iff",
  hex: "46 4F 52 4D nn nn nn nn 49 4C 42 4D",
  offset: "any"},
  {ascii: "FORM.... 8SVX",
  description: "IFF8-Bit Sampled Voice",
  file_extension: "8svx",
  hex: "46 4F 52 4D nn nn nn nn 38 53 56 58",
  offset: "any"},
  {ascii: "FORM.... 8SVX",
  description: "IFF8-Bit Sampled Voice",
  file_extension: "8sv",
  hex: "46 4F 52 4D nn nn nn nn 38 53 56 58",
  offset: "any"},
  {ascii: "FORM.... 8SVX",
  description: "IFF8-Bit Sampled Voice",
  file_extension: "svx",
  hex: "46 4F 52 4D nn nn nn nn 38 53 56 58",
  offset: "any"},
  {ascii: "FORM.... 8SVX",
  description: "IFF8-Bit Sampled Voice",
  file_extension: "snd",
  hex: "46 4F 52 4D nn nn nn nn 38 53 56 58",
  offset: "any"},
  {ascii: "FORM.... 8SVX",
  description: "IFF8-Bit Sampled Voice",
  file_extension: "iff",
  hex: "46 4F 52 4D nn nn nn nn 38 53 56 58",
  offset: "any"},
  {ascii: "FORM.... ACBM",
  description: "Amiga Contiguous Bitmap",
  file_extension: "acbm",
  hex: "46 4F 52 4D nn nn nn nn 41 43 42 4D",
  offset: "any"},
  {ascii: "FORM.... ACBM",
  description: "Amiga Contiguous Bitmap",
  file_extension: "iff",
  hex: "46 4F 52 4D nn nn nn nn 41 43 42 4D",
  offset: "any"},
  {ascii: "FORM.... ANBM",
  description: "IFFAnimated Bitmap",
  file_extension: "anbm",
  hex: "46 4F 52 4D nn nn nn nn 41 4E 42 4D",
  offset: "any"},
  {ascii: "FORM.... ANBM",
  description: "IFFAnimated Bitmap",
  file_extension: "iff",
  hex: "46 4F 52 4D nn nn nn nn 41 4E 42 4D",
  offset: "any"},
  {ascii: "FORM.... ANIM",
  description: "IFFCEL Animation",
  file_extension: "anim",
  hex: "46 4F 52 4D nn nn nn nn 41 4E 49 4D",
  offset: "any"},
  {ascii: "FORM.... ANIM",
  description: "IFFCEL Animation",
  file_extension: "iff",
  hex: "46 4F 52 4D nn nn nn nn 41 4E 49 4D",
  offset: "any"},
  {ascii: "FORM.... FAXX",
  description: "IFFFacsimile Image",
  file_extension: "faxx",
  hex: "46 4F 52 4D nn nn nn nn 46 41 58 58",
  offset: "any"},
  {ascii: "FORM.... FAXX",
  description: "IFFFacsimile Image",
  file_extension: "faxx",
  hex: "46 4F 52 4D nn nn nn nn 46 41 58 58",
  offset: "any"},
  {ascii: "FORM.... FAXX",
  description: "IFFFacsimile Image",
  file_extension: "iff",
  hex: "46 4F 52 4D nn nn nn nn 46 41 58 58",
  offset: "any"},
  {ascii: "FORM.... FTXT",
  description: "IFFFormatted Text",
  file_extension: "ftxt",
  hex: "46 4F 52 4D nn nn nn nn 46 54 58 54",
  offset: "any"},
  {ascii: "FORM.... FTXT",
  description: "IFFFormatted Text",
  file_extension: "txt",
  hex: "46 4F 52 4D nn nn nn nn 46 54 58 54",
  offset: "any"},
  {ascii: "FORM.... FTXT",
  description: "IFFFormatted Text",
  file_extension: "iff",
  hex: "46 4F 52 4D nn nn nn nn 46 54 58 54",
  offset: "any"},
  {ascii: "FORM.... SMUS",
  description: "IFFSimple Musical Score",
  file_extension: "smus",
  hex: "46 4F 52 4D nn nn nn nn 53 4D 55 53",
  offset: "any"},
  {ascii: "FORM.... SMUS",
  description: "IFFSimple Musical Score",
  file_extension: "smu",
  hex: "46 4F 52 4D nn nn nn nn 53 4D 55 53",
  offset: "any"},
  {ascii: "FORM.... SMUS",
  description: "IFFSimple Musical Score",
  file_extension: "mus",
  hex: "46 4F 52 4D nn nn nn nn 53 4D 55 53",
  offset: "any"},
  {ascii: "FORM.... SMUS",
  description: "IFFSimple Musical Score",
  file_extension: "iff",
  hex: "46 4F 52 4D nn nn nn nn 53 4D 55 53",
  offset: "any"},
  {ascii: "FORM.... CMUS",
  description: "IFFMusical Score",
  file_extension: "cmus",
  hex: "46 4F 52 4D nn nn nn nn 43 4D 55 53",
  offset: "any"},
  {ascii: "FORM.... CMUS",
  description: "IFFMusical Score",
  file_extension: "mus",
  hex: "46 4F 52 4D nn nn nn nn 43 4D 55 53",
  offset: "any"},
  {ascii: "FORM.... CMUS",
  description: "IFFMusical Score",
  file_extension: "iff",
  hex: "46 4F 52 4D nn nn nn nn 43 4D 55 53",
  offset: "any"},
  {ascii: "FORM.... YUVN",
  description: "IFFYUV Image",
  file_extension: "yuvn",
  hex: "46 4F 52 4D nn nn nn nn 59 55 56 4E",
  offset: "any"},
  {ascii: "FORM.... YUVN",
  description: "IFFYUV Image",
  file_extension: "yuv",
  hex: "46 4F 52 4D nn nn nn nn 59 55 56 4E",
  offset: "any"},
  {ascii: "FORM.... YUVN",
  description: "IFFYUV Image",
  file_extension: "iff",
  hex: "46 4F 52 4D nn nn nn nn 59 55 56 4E",
  offset: "any"},
  {ascii: "FORM.... FANT",
  description: "AmigaFantavision Movie",
  file_extension: "iff",
  hex: "46 4F 52 4D nn nn nn nn 46 41 4E 54",
  offset: "any"},
  {ascii: "FORM.... AIFF",
  description: "Audio Interchange File Format",
  file_extension: "aiff",
  hex: "46 4F 52 4D nn nn nn nn 41 49 46 46",
  offset: "any"},
  {ascii: "FORM.... AIFF",
  description: "Audio Interchange File Format",
  file_extension: "aif",
  hex: "46 4F 52 4D nn nn nn nn 41 49 46 46",
  offset: "any"},
  {ascii: "FORM.... AIFF",
  description: "Audio Interchange File Format",
  file_extension: "aifc",
  hex: "46 4F 52 4D nn nn nn nn 41 49 46 46",
  offset: "any"},
  {ascii: "FORM.... AIFF",
  description: "Audio Interchange File Format",
  file_extension: "snd",
  hex: "46 4F 52 4D nn nn nn nn 41 49 46 46",
  offset: "any"},
  {ascii: "FORM.... AIFF",
  description: "Audio Interchange File Format",
  file_extension: "iff",
  hex: "46 4F 52 4D nn nn nn nn 41 49 46 46",
  offset: "any"},
  {ascii: "INDX",
  description: "Index file to a file ortape containing abackup done withAmiBack on anAmiga.",
  file_extension: "idx",
  hex: "49 4E 44 58",
  offset: "0"},
  {ascii: "LZIP",
  description: "lzip compressed file",
  file_extension: "lz",
  hex: "4C 5A 49 50",
  offset: "0"},
  {ascii: "MZ",
  description: "DOS MZ executable file format and its descendants (includingNE andPE)",
  file_extension: "exe",
  hex: "4D 5A",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML",
  file_extension: "zip",
  hex: "50 4B 03 04",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML",
  file_extension: "jar",
  hex: "50 4B 03 04",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML",
  file_extension: "odt",
  hex: "50 4B 03 04",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML",
  file_extension: "ods",
  hex: "50 4B 03 04",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML",
  file_extension: "odp",
  hex: "50 4B 03 04",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML",
  file_extension: "docx",
  hex: "50 4B 03 04",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML",
  file_extension: "xlsx",
  hex: "50 4B 03 04",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML",
  file_extension: "pptx",
  hex: "50 4B 03 04",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML",
  file_extension: "vsdx",
  hex: "50 4B 03 04",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML",
  file_extension: "apk",
  hex: "50 4B 03 04",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
  file_extension: "zip",
  hex: "50 4B 05 06",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
  file_extension: "jar",
  hex: "50 4B 05 06",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
  file_extension: "odt",
  hex: "50 4B 05 06",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
  file_extension: "ods",
  hex: "50 4B 05 06",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
  file_extension: "odp",
  hex: "50 4B 05 06",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
  file_extension: "docx",
  hex: "50 4B 05 06",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
  file_extension: "xlsx",
  hex: "50 4B 05 06",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
  file_extension: "pptx",
  hex: "50 4B 05 06",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
  file_extension: "vsdx",
  hex: "50 4B 05 06",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (empty archive)",
  file_extension: "apk",
  hex: "50 4B 05 06",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
  file_extension: "zip",
  hex: "50 4B 07 08",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
  file_extension: "jar",
  hex: "50 4B 07 08",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
  file_extension: "odt",
  hex: "50 4B 07 08",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
  file_extension: "ods",
  hex: "50 4B 07 08",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
  file_extension: "odp",
  hex: "50 4B 07 08",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
  file_extension: "docx",
  hex: "50 4B 07 08",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
  file_extension: "xlsx",
  hex: "50 4B 07 08",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
  file_extension: "pptx",
  hex: "50 4B 07 08",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
  file_extension: "vsdx",
  hex: "50 4B 07 08",
  offset: "0"},
  {ascii: "PK..",
  description: "zip file format and formats based on it, such asJAR,ODF,OOXML (spanned archive)",
  file_extension: "apk",
  hex: "50 4B 07 08",
  offset: "0"},
  {ascii: "Rar!...",
  description: "RAR archive version 1.50 onwards",
  file_extension: "rar",
  hex: "52 61 72 21 1A 07 00",
  offset: "0"},
  {ascii: "Rar!....",
  description: "RAR archive version 5.0 onwards",
  file_extension: "rar",
  hex: "52 61 72 21 1A 07 01 00",
  offset: "0"},
  {ascii: ".ELF",
  description: "Executable and Linkable Format",
  file_extension: "",
  hex: "7F 45 4C 46",
  offset: "0"},
  {ascii: ".PNG....",
  description: "Image encoded in thePortable Network Graphics format",
  file_extension: "png",
  hex: "89 50 4E 47 0D 0A 1A 0A",
  offset: "0"},
  {ascii: "Êþº¾",
  description: "Java class file,Mach-O Fat Binary",
  file_extension: "class",
  hex: "CA FE BA BE",
  offset: "0"},
  {ascii: "ï»¿",
  description: "UTF-8 encodedUnicodebyte order mark, commonly seen in text files.",
  file_extension: "",
  hex: "EF BB BF",
  offset: "0"},
  {ascii: "........",
  description: "Mach-O binary (32-bit)",
  file_extension: "",
  hex: "FE ED FA CE",
  offset: "0"},
  {ascii: "........",
  description: "Mach-O binary (32-bit)",
  file_extension: "",
  hex: "FE ED FA CE",
  offset: "0x1000"},
  {ascii: "........",
  description: "Mach-O binary (64-bit)",
  file_extension: "",
  hex: "FE ED FA CF",
  offset: "0"},
  {ascii: "........",
  description: "Mach-O binary (64-bit)",
  file_extension: "",
  hex: "FE ED FA CF",
  offset: "0x1000"},
  {ascii: "........",
  description: "Mach-O binary (reverse byte ordering scheme, 32-bit)",
  file_extension: "",
  hex: "CE FA ED FE",
  offset: "0"},
  {ascii: "........",
  description: "Mach-O binary (reverse byte ordering scheme, 64-bit)",
  file_extension: "",
  hex: "CF FA ED FE",
  offset: "0"},
  {ascii: "..",
  description: "Byte-order mark for text file encoded inlittle-endian16-bit Unicode Transfer Format",
  file_extension: "",
  hex: "FF FE",
  offset: "0"},
  {ascii: "....",
  description: "Byte-order mark for text file encoded in little-endian32-bit Unicode Transfer Format",
  file_extension: "",
  hex: "FF FE 00 00",
  offset: "0"},
  {ascii: "%!PS",
  description: "PostScript document",
  file_extension: "ps",
  hex: "25 21 50 53",
  offset: "0"},
  {ascii: "%PDF",
  description: "PDF document",
  file_extension: "pdf",
  hex: "25 50 44 46",
  offset: "0"},
  {ascii: "0&²u.fÏ .¦Ù.ª.bÎl",
  description: "Advanced Systems Format",
  file_extension: "asf",
  hex: "30 26 B2 75 8E 66 CF 11 A6 D9 00 AA 00 62 CE 6C",
  offset: "0"},
  {ascii: "0&²u.fÏ .¦Ù.ª.bÎl",
  description: "Advanced Systems Format",
  file_extension: "wma",
  hex: "30 26 B2 75 8E 66 CF 11 A6 D9 00 AA 00 62 CE 6C",
  offset: "0"},
  {ascii: "0&²u.fÏ .¦Ù.ª.bÎl",
  description: "Advanced Systems Format",
  file_extension: "wmv",
  hex: "30 26 B2 75 8E 66 CF 11 A6 D9 00 AA 00 62 CE 6C",
  offset: "0"},
  {ascii: "$SDI0001",
  description: "System Deployment Image, a disk image format used byMicrosoft",
  file_extension: "",
  hex: "24 53 44 49 30 30 30 31",
  offset: "0"},
  {ascii: "OggS",
  description: "Ogg, anopen source media container format",
  file_extension: "ogg",
  hex: "4F 67 67 53",
  offset: "0"},
  {ascii: "OggS",
  description: "Ogg, anopen source media container format",
  file_extension: "oga",
  hex: "4F 67 67 53",
  offset: "0"},
  {ascii: "OggS",
  description: "Ogg, anopen source media container format",
  file_extension: "ogv",
  hex: "4F 67 67 53",
  offset: "0"},
  {ascii: "8BPS",
  description: "Photoshop Document file,Adobe Photoshop's native file format",
  file_extension: "psd",
  hex: "38 42 50 53",
  offset: "0"},
  {ascii: "RIFF.... WAVE",
  description: "Waveform Audio File Format",
  file_extension: "wav",
  hex: "52 49 46 46 nn nn nn nn 57 41 56 45",
  offset: "0"},
  {ascii: "RIFF.... AVI.",
  description: "Audio Video Interleave video format",
  file_extension: "avi",
  hex: "52 49 46 46 nn nn nn nn 41 56 49 20",
  offset: "0"},
  {ascii: "ÿû",
  description: "MPEG-1 Layer 3 file without anID3 tag or with anID3v1 tag (which's appended at the end of the file)",
  file_extension: "mp3",
  hex: "FF FB",
  offset: "0"},
  {ascii: "ID3",
  description: "MP3 file with an ID3v2 container",
  file_extension: "mp3",
  hex: "49 44 33",
  offset: "0"},
  {ascii: "BM",
  description: "BMP file, abitmap format used mostly in theWindows world",
  file_extension: "bmp",
  hex: "42 4D",
  offset: "0"},
  {ascii: "BM",
  description: "BMP file, abitmap format used mostly in theWindows world",
  file_extension: "dib",
  hex: "42 4D",
  offset: "0"},
  {ascii: "BM",
  description: "BMP file, abitmap format used mostly in theWindows world",
  file_extension: "bmp",
  hex: "42 4D",
  offset: "0"},
  {ascii: "BM",
  description: "BMP file, abitmap format used mostly in theWindows world",
  file_extension: "dib",
  hex: "42 4D",
  offset: "0"},
  {ascii: "CD001",
  description: "ISO9660 CD/DVD image file",
  file_extension: "iso",
  hex: "43 44 30 30 31",
  offset: "0x8001"},
  {ascii: "CD001",
  description: "ISO9660 CD/DVD image file",
  file_extension: "iso",
  hex: "43 44 30 30 31",
  offset: "0x8801"},
  {ascii: "CD001",
  description: "ISO9660 CD/DVD image file",
  file_extension: "iso",
  hex: "43 44 30 30 31",
  offset: "0x9001"},
  {ascii: "SIMPLE   =         T",
  description: "Flexible Image Transport System (FITS)",
  file_extension: "fits",
  hex: "53 49 4D 50 4C 45 20 20 3D 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 54",
  offset: "0"},
  {ascii: "fLaC",
  description: "Free Lossless Audio Codec",
  file_extension: "flac",
  hex: "66 4C 61 43",
  offset: "0"},
  {ascii: "MThd",
  description: "MIDI sound file",
  file_extension: "mid",
  hex: "4D 54 68 64",
  offset: "0"},
  {ascii: "MThd",
  description: "MIDI sound file",
  file_extension: "midi",
  hex: "4D 54 68 64",
  offset: "0"},
  {ascii: "",
  description: "Compound File Binary Format, a container format used for document by older versions ofMicrosoft Office.It is however an open format used by other programs as well.",
  file_extension: "doc",
  hex: "D0 CF 11 E0 A1 B1 1A E1",
  offset: ""},
  {ascii: "",
  description: "Compound File Binary Format, a container format used for document by older versions ofMicrosoft Office.It is however an open format used by other programs as well.",
  file_extension: "xls",
  hex: "D0 CF 11 E0 A1 B1 1A E1",
  offset: ""},
  {ascii: "",
  description: "Compound File Binary Format, a container format used for document by older versions ofMicrosoft Office.It is however an open format used by other programs as well.",
  file_extension: "ppt",
  hex: "D0 CF 11 E0 A1 B1 1A E1",
  offset: ""},
  {ascii: "",
  description: "Compound File Binary Format, a container format used for document by older versions ofMicrosoft Office.It is however an open format used by other programs as well.",
  file_extension: "msg",
  hex: "D0 CF 11 E0 A1 B1 1A E1",
  offset: ""},
  {ascii: "dex.035.",
  description: "Dalvik Executable",
  file_extension: "dex",
  hex: "64 65 78 0A 30 33 35 00",
  offset: "0"},
  {ascii: "KDM",
  description: "VMDK files",
  file_extension: "vmdk",
  hex: "4B 44 4D",
  offset: "0"},
  {ascii: "Cr24",
  description: "Google Chrome extensionor packaged app",
  file_extension: "crx",
  hex: "43 72 32 34",
  offset: "0"},
  {ascii: "AGD3",
  description: "FreeHand 8 document",
  file_extension: "fh8",
  hex: "41 47 44 33",
  offset: "0"},
  {ascii: "....BOBO ........ ....",
  description: "AppleWorks 5 document",
  file_extension: "cwk",
  hex: "05 07 00 00 42 4F 42 4F 05 07 00 00 00 00 00 00 00 00 00 00 00 01",
  offset: "0"},
  {ascii: "....BOBO ........ ....",
  description: "AppleWorks 6 document",
  file_extension: "cwk",
  hex: "06 07 E1 00 42 4F 42 4F 06 07 E1 00 00 00 00 00 00 00 00 00 00 01",
  offset: "0"},
  {ascii: "ER....ãER....",
  description: "RoxioToast disc image file, also some .dmg-files begin with same bytes",
  file_extension: "toast",
  hex: "45 52 02 00 00 00 8B 45 52 02 00 00 00",
  offset: "0"},
  {ascii: "x.s.bb`",
  description: "Apple Disk Image file",
  file_extension: "dmg",
  hex: "78 01 73 0D 62 62 60",
  offset: "0"},
  {ascii: "xar!",
  description: "eXtensible Archive format",
  file_extension: "xar",
  hex: "78 61 72 21",
  offset: "0"},
  {ascii: "PMOCCMOC",
  description: "Windows Files And Settings Transfer Repository, See also USMT 3.0 (Win XP) and USMT 4.0 (Win 7) User Guides",
  file_extension: "dat",
  hex: "50 4D 4F 43 43 4D 4F 43",
  offset: "0"},
  {ascii: "NES",
  description: "Nintendo Entertainment System ROM file",
  file_extension: "nes",
  hex: "4E 45 53 1A",
  offset: "0"},
  {ascii: "ustar.00ustar  .",
  description: "tar archive",
  file_extension: "tar",
  hex: "75 73 74 61 72 00 30 30 75 73 74 61 72 20 20 00",
  offset: "0x101"},
  {ascii: "TOX",
  description: "Open source portable voxel file",
  file_extension: "tox",
  hex: "74 6F 78 33",
  offset: "0"},
  {ascii: "MLVI",
  description: "Magic Lantern Video file",
  file_extension: "MLV",
  hex: "4D 4C 56 49",
  offset: "0"},
  {ascii: "DCM PA30",
  description: "Windows UpdateBinary Delta Compression",
  file_extension: "",
  hex: "44 43 4D 01 50 41 33 30",
  offset: "0"},
  {ascii: "7z¼¯",
  description: "7-Zip File Format",
  file_extension: "7z",
  hex: "37 7A BC AF 27 1C",
  offset: "0"},
  {ascii: "..",
  description: "GZIP",
  file_extension: "gz",
  hex: "1F 8B",
  offset: "0"},
  {ascii: "..",
  description: "GZIP",
  file_extension: "tar.gz",
  hex: "1F 8B",
  offset: "0"},
  {ascii: ".M.",
  description: "LZ4 Frame Format, LZ4 block format does not offer any magic bytes.",
  file_extension: "lz4",
  hex: "04 22 4D 18",
  offset: "0"},
  {ascii: "MSCF",
  description: "Microsoft Cabinet file",
  file_extension: "cab",
  hex: "4D 53 43 46",
  offset: "0"},
  {ascii: "FLIF",
  description: "Free Lossless Image Format",
  file_extension: "flif",
  hex: "46 4C 49 46",
  offset: "0"},
  {ascii: ".Eß£",
  description: "Matroska media container, includingWebM",
  file_extension: "mkv",
  hex: "1A 45 DF A3",
  offset: "0"},
  {ascii: ".Eß£",
  description: "Matroska media container, includingWebM",
  file_extension: "mka",
  hex: "1A 45 DF A3",
  offset: "0"},
  {ascii: ".Eß£",
  description: "Matroska media container, includingWebM",
  file_extension: "mks",
  hex: "1A 45 DF A3",
  offset: "0"},
  {ascii: ".Eß£",
  description: "Matroska media container, includingWebM",
  file_extension: "mk3d",
  hex: "1A 45 DF A3",
  offset: "0"},
  {ascii: ".Eß£",
  description: "Matroska media container, includingWebM",
  file_extension: "webm",
  hex: "1A 45 DF A3",
  offset: "0"},
  {ascii: "MIL",
  description: "SEAN\xa0: Session Analysis Training file. Also used in compatible software 'Rpw\xa0:Rowperfect for Windows' and 'RP3W\xa0: ROWPERFECT3 for Windows'.",
  file_extension: "stg",
  hex: "4D 49 4C 20",
  offset: "0"},
  {ascii: "AT&TFORM....DJV",
  description: "DjVu document. The following byte is either55 (U) for single-page or4D (M) for multi-page documents.",
  file_extension: "['djvu', 'djv']",
  hex: "41 54 26 54 46 4F 52 4D nn nn nn nn 44 4A 56",
  offset: "0"},
  {ascii: "AT&TFORM....DJV",
  description: "DjVu document. The following byte is either55 (U) for single-page or4D (M) for multi-page documents.",
  file_extension: "djvu",
  hex: "41 54 26 54 46 4F 52 4D nn nn nn nn 44 4A 56",
  offset: "0"},
  {ascii: "AT&TFORM....DJV",
  description: "DjVu document. The following byte is either55 (U) for single-page or4D (M) for multi-page documents.",
  file_extension: "djv",
  hex: "41 54 26 54 46 4F 52 4D nn nn nn nn 44 4A 56",
  offset: "0"},
  {ascii: "0.",
  description: "DER encoded X.509 certificate",
  file_extension: "der",
  hex: "30 82",
  offset: "0"},
  {ascii: "DICM",
  description: "DICOM Medical File Format",
  file_extension: "dcm",
  hex: "44 49 43 4D",
  offset: "0x80"},
  {ascii: "wOFF",
  description: "WOFF File Format 1.0",
  file_extension: "woff",
  hex: "77 4F 46 46",
  offset: "0"},
  {ascii: "wOF2",
  description: "WOFF File Format 2.0",
  file_extension: "woff2",
  hex: "77 4F 46 32",
  offset: "0"},
  {ascii: "<?xml",
  description: "eXtensible Markup Language when using theASCII character encoding",
  file_extension: "XML",
  hex: "3c 3f 78 6d 6c 20",
  offset: "0"},
  {ascii: "\\0asm",
  description: "WebAssembly binary format",
  file_extension: "wasm",
  hex: "6d 73 61 00",
  offset: "0"},
  {ascii: "",
  description: "Lepton compressed JPEG image",
  file_extension: "lep",
  hex: "cf 84 01",
  offset: "0"},
  {ascii: "CWS",
  description: "flash .swf",
  file_extension: "swf",
  hex: "43 57 53",
  offset: "0"},
  {ascii: "EWS",
  description: "flash .swf",
  file_extension: "swf",
  hex: "46 57 53",
  offset: "0"},
  {ascii: "!<arch>.",
  description: "linux deb file",
  file_extension: "deb",
  hex: "21 3C 61 72 63 68 3E",
  offset: "0"},
  {ascii: "RIFF....",
  description: "Google WebP image file",
  file_extension: "webp",
  hex: "52 49 46 46 nn nn nn nn",
  offset: "0"},
  {ascii: "WEBP",
  description: "",
  file_extension: "",
  hex: "57 45 42 50",
  offset: ""},
  {ascii: "..V",
  description: "U-Boot / uImage.Das_U-Boot Universal Boot Loader.",
  file_extension: "",
  hex: "27 05 19 56",
  offset: "0"}
  ]

  fileExtensionMimeTypeMap: { [id: string] : string; } = {
    ".123" : "application/vnd.lotus-1-2-3",
    ".3dml" : "text/vnd.in3d.3dml",
    ".3g2" : "video/3gpp2",
    ".3gp" : "video/3gpp",
    ".a" : "application/octet-stream",
    ".aab" : "application/x-authorware-bin",
    ".aac" : "audio/x-aac",
    ".aam" : "application/x-authorware-map",
    ".aas" : "application/x-authorware-seg",
    ".abw" : "application/x-abiword",
    ".acc" : "application/vnd.americandynamics.acc",
    ".ace" : "application/x-ace-compressed",
    ".acu" : "application/vnd.acucobol",
    ".acutc" : "application/vnd.acucorp",
    ".adp" : "audio/adpcm",
    ".aep" : "application/vnd.audiograph",
    ".afm" : "application/x-font-type1",
    ".afp" : "application/vnd.ibm.modcap",
    ".ai" : "application/postscript",
    ".aif" : "audio/x-aiff",
    ".aifc" : "audio/x-aiff",
    ".aiff" : "audio/x-aiff",
    ".air" : "application/vnd.adobe.air-application-installer-package+zip",
    ".ami" : "application/vnd.amiga.ami",
    ".apk" : "application/vnd.android.package-archive",
    ".application" : "application/x-ms-application",
    ".apr" : "application/vnd.lotus-approach",
    ".asc" : "application/pgp-signature",
    ".asf" : "video/x-ms-asf",
    ".asm" : "text/x-asm",
    ".aso" : "application/vnd.accpac.simply.aso",
    ".asx" : "video/x-ms-asf",
    ".atc" : "application/vnd.acucorp",
    ".atom" : "application/atom+xml",
    ".atomcat" : "application/atomcat+xml",
    ".atomsvc" : "application/atomsvc+xml",
    ".atx" : "application/vnd.antix.game-component",
    ".au" : "audio/basic",
    ".avi" : "video/x-msvideo",
    ".aw" : "application/applixware",
    ".azf" : "application/vnd.airzip.filesecure.azf",
    ".azs" : "application/vnd.airzip.filesecure.azs",
    ".azw" : "application/vnd.amazon.ebook",
    ".bat" : "application/x-msdownload",
    ".bcpio" : "application/x-bcpio",
    ".bdf" : "application/x-font-bdf",
    ".bdm" : "application/vnd.syncml.dm+wbxml",
    ".bh2" : "application/vnd.fujitsu.oasysprs",
    ".bin" : "application/octet-stream",
    ".bmi" : "application/vnd.bmi",
    ".bmp" : "image/bmp",
    ".book" : "application/vnd.framemaker",
    ".box" : "application/vnd.previewsystems.box",
    ".boz" : "application/x-bzip2",
    ".bpk" : "application/octet-stream",
    ".btif" : "image/prs.btif",
    ".bz" : "application/x-bzip",
    ".bz2" : "application/x-bzip2",
    ".c" : "text/x-c",
    ".c4d" : "application/vnd.clonk.c4group",
    ".c4f" : "application/vnd.clonk.c4group",
    ".c4g" : "application/vnd.clonk.c4group",
    ".c4p" : "application/vnd.clonk.c4group",
    ".c4u" : "application/vnd.clonk.c4group",
    ".cab" : "application/vnd.ms-cab-compressed",
    ".car" : "application/vnd.curl.car",
    ".cat" : "application/vnd.ms-pki.seccat",
    ".cc" : "text/x-c",
    ".cct" : "application/x-director",
    ".ccxml" : "application/ccxml+xml",
    ".cdbcmsg" : "application/vnd.contact.cmsg",
    ".cdf" : "application/x-netcdf",
    ".cdkey" : "application/vnd.mediastation.cdkey",
    ".cdx" : "chemical/x-cdx",
    ".cdxml" : "application/vnd.chemdraw+xml",
    ".cdy" : "application/vnd.cinderella",
    ".cer" : "application/pkix-cert",
    ".cgm" : "image/cgm",
    ".chat" : "application/x-chat",
    ".chm" : "application/vnd.ms-htmlhelp",
    ".chrt" : "application/vnd.kde.kchart",
    ".cif" : "chemical/x-cif",
    ".cii" : "application/vnd.anser-web-certificate-issue-initiation",
    ".cil" : "application/vnd.ms-artgalry",
    ".cla" : "application/vnd.claymore",
    ".class" : "application/java-vm",
    ".clkk" : "application/vnd.crick.clicker.keyboard",
    ".clkp" : "application/vnd.crick.clicker.palette",
    ".clkt" : "application/vnd.crick.clicker.template",
    ".clkw" : "application/vnd.crick.clicker.wordbank",
    ".clkx" : "application/vnd.crick.clicker",
    ".clp" : "application/x-msclip",
    ".cmc" : "application/vnd.cosmocaller",
    ".cmdf" : "chemical/x-cmdf",
    ".cml" : "chemical/x-cml",
    ".cmp" : "application/vnd.yellowriver-custom-menu",
    ".cmx" : "image/x-cmx",
    ".cod" : "application/vnd.rim.cod",
    ".com" : "application/x-msdownload",
    ".conf" : "text/plain",
    ".cpio" : "application/x-cpio",
    ".cpp" : "text/x-c",
    ".cpt" : "application/mac-compactpro",
    ".crd" : "application/x-mscardfile",
    ".crl" : "application/pkix-crl",
    ".crt" : "application/x-x509-ca-cert",
    ".csh" : "application/x-csh",
    ".csml" : "chemical/x-csml",
    ".csp" : "application/vnd.commonspace",
    ".css" : "text/css",
    ".cst" : "application/x-director",
    ".csv" : "text/csv",
    ".cu" : "application/cu-seeme",
    ".curl" : "text/vnd.curl",
    ".cww" : "application/prs.cww",
    ".cxt" : "application/x-director",
    ".cxx" : "text/x-c",
    ".daf" : "application/vnd.mobius.daf",
    ".dataless" : "application/vnd.fdsn.seed",
    ".davmount" : "application/davmount+xml",
    ".dcr" : "application/x-director",
    ".dcurl" : "text/vnd.curl.dcurl",
    ".dd2" : "application/vnd.oma.dd2+xml",
    ".ddd" : "application/vnd.fujixerox.ddd",
    ".deb" : "application/x-debian-package",
    ".def" : "text/plain",
    ".deploy" : "application/octet-stream",
    ".der" : "application/x-x509-ca-cert",
    ".dfac" : "application/vnd.dreamfactory",
    ".dic" : "text/x-c",
    ".diff" : "text/plain",
    ".dir" : "application/x-director",
    ".dis" : "application/vnd.mobius.dis",
    ".dist" : "application/octet-stream",
    ".distz" : "application/octet-stream",
    ".djv" : "image/vnd.djvu",
    ".djvu" : "image/vnd.djvu",
    ".dll" : "application/x-msdownload",
    ".dmg" : "application/octet-stream",
    ".dms" : "application/octet-stream",
    ".dna" : "application/vnd.dna",
    ".doc" : "application/msword",
    ".docm" : "application/vnd.ms-word.document.macroenabled.12",
    ".docx" : "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ".dot" : "application/msword",
    ".dotm" : "application/vnd.ms-word.template.macroenabled.12",
    ".dotx" : "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
    ".dp" : "application/vnd.osgi.dp",
    ".dpg" : "application/vnd.dpgraph",
    ".dsc" : "text/prs.lines.tag",
    ".dtb" : "application/x-dtbook+xml",
    ".dtd" : "application/xml-dtd",
    ".dts" : "audio/vnd.dts",
    ".dtshd" : "audio/vnd.dts.hd",
    ".dump" : "application/octet-stream",
    ".dvi" : "application/x-dvi",
    ".dwf" : "model/vnd.dwf",
    ".dwg" : "image/vnd.dwg",
    ".dxf" : "image/vnd.dxf",
    ".dxp" : "application/vnd.spotfire.dxp",
    ".dxr" : "application/x-director",
    ".ecelp4800" : "audio/vnd.nuera.ecelp4800",
    ".ecelp7470" : "audio/vnd.nuera.ecelp7470",
    ".ecelp9600" : "audio/vnd.nuera.ecelp9600",
    ".ecma" : "application/ecmascript",
    ".edm" : "application/vnd.novadigm.edm",
    ".edx" : "application/vnd.novadigm.edx",
    ".efif" : "application/vnd.picsel",
    ".ei6" : "application/vnd.pg.osasli",
    ".elc" : "application/octet-stream",
    ".eml" : "message/rfc822",
    ".emma" : "application/emma+xml",
    ".eol" : "audio/vnd.digital-winds",
    ".eot" : "application/vnd.ms-fontobject",
    ".eps" : "application/postscript",
    ".epub" : "application/epub+zip",
    ".es3" : "application/vnd.eszigno3+xml",
    ".esf" : "application/vnd.epson.esf",
    ".et3" : "application/vnd.eszigno3+xml",
    ".etx" : "text/x-setext",
    ".exe" : "application/x-msdownload",
    ".ext" : "application/vnd.novadigm.ext",
    ".ez" : "application/andrew-inset",
    ".ez2" : "application/vnd.ezpix-album",
    ".ez3" : "application/vnd.ezpix-package",
    ".f" : "text/x-fortran",
    ".f4v" : "video/x-f4v",
    ".f77" : "text/x-fortran",
    ".f90" : "text/x-fortran",
    ".fbs" : "image/vnd.fastbidsheet",
    ".fdf" : "application/vnd.fdf",
    ".fe_launch" : "application/vnd.denovo.fcselayout-link",
    ".fg5" : "application/vnd.fujitsu.oasysgp",
    ".fgd" : "application/x-director",
    ".fh" : "image/x-freehand",
    ".fh4" : "image/x-freehand",
    ".fh5" : "image/x-freehand",
    ".fh7" : "image/x-freehand",
    ".fhc" : "image/x-freehand",
    ".fig" : "application/x-xfig",
    ".fli" : "video/x-fli",
    ".flo" : "application/vnd.micrografx.flo",
    ".flv" : "video/x-flv",
    ".flw" : "application/vnd.kde.kivio",
    ".flx" : "text/vnd.fmi.flexstor",
    ".fly" : "text/vnd.fly",
    ".fm" : "application/vnd.framemaker",
    ".fnc" : "application/vnd.frogans.fnc",
    ".for" : "text/x-fortran",
    ".fpx" : "image/vnd.fpx",
    ".frame" : "application/vnd.framemaker",
    ".fsc" : "application/vnd.fsc.weblaunch",
    ".fst" : "image/vnd.fst",
    ".ftc" : "application/vnd.fluxtime.clip",
    ".fti" : "application/vnd.anser-web-funds-transfer-initiation",
    ".fvt" : "video/vnd.fvt",
    ".fzs" : "application/vnd.fuzzysheet",
    ".g3" : "image/g3fax",
    ".gac" : "application/vnd.groove-account",
    ".gdl" : "model/vnd.gdl",
    ".geo" : "application/vnd.dynageo",
    ".gex" : "application/vnd.geometry-explorer",
    ".ggb" : "application/vnd.geogebra.file",
    ".ggt" : "application/vnd.geogebra.tool",
    ".ghf" : "application/vnd.groove-help",
    ".gif" : "image/gif",
    ".gim" : "application/vnd.groove-identity-message",
    ".gmx" : "application/vnd.gmx",
    ".gnumeric" : "application/x-gnumeric",
    ".gph" : "application/vnd.flographit",
    ".gqf" : "application/vnd.grafeq",
    ".gqs" : "application/vnd.grafeq",
    ".gram" : "application/srgs",
    ".gre" : "application/vnd.geometry-explorer",
    ".grv" : "application/vnd.groove-injector",
    ".grxml" : "application/srgs+xml",
    ".gsf" : "application/x-font-ghostscript",
    ".gtar" : "application/x-gtar",
    ".gtm" : "application/vnd.groove-tool-message",
    ".gtw" : "model/vnd.gtw",
    ".gv" : "text/vnd.graphviz",
    ".gz" : "application/x-gzip",
    ".h" : "text/x-c",
    ".h261" : "video/h261",
    ".h263" : "video/h263",
    ".h264" : "video/h264",
    ".hbci" : "application/vnd.hbci",
    ".hdf" : "application/x-hdf",
    ".hh" : "text/x-c",
    ".hlp" : "application/winhlp",
    ".hpgl" : "application/vnd.hp-hpgl",
    ".hpid" : "application/vnd.hp-hpid",
    ".hps" : "application/vnd.hp-hps",
    ".hqx" : "application/mac-binhex40",
    ".htke" : "application/vnd.kenameaapp",
    ".htm" : "text/html",
    ".html" : "text/html",
    ".hvd" : "application/vnd.yamaha.hv-dic",
    ".hvp" : "application/vnd.yamaha.hv-voice",
    ".hvs" : "application/vnd.yamaha.hv-script",
    ".icc" : "application/vnd.iccprofile",
    ".ice" : "x-conference/x-cooltalk",
    ".icm" : "application/vnd.iccprofile",
    ".ico" : "image/x-icon",
    ".ics" : "text/calendar",
    ".ief" : "image/ief",
    ".ifb" : "text/calendar",
    ".ifm" : "application/vnd.shana.informed.formdata",
    ".iges" : "model/iges",
    ".igl" : "application/vnd.igloader",
    ".igs" : "model/iges",
    ".igx" : "application/vnd.micrografx.igx",
    ".iif" : "application/vnd.shana.informed.interchange",
    ".imp" : "application/vnd.accpac.simply.imp",
    ".ims" : "application/vnd.ms-ims",
    ".in" : "text/plain",
    ".ipk" : "application/vnd.shana.informed.package",
    ".irm" : "application/vnd.ibm.rights-management",
    ".irp" : "application/vnd.irepository.package+xml",
    ".iso" : "application/octet-stream",
    ".itp" : "application/vnd.shana.informed.formtemplate",
    ".ivp" : "application/vnd.immervision-ivp",
    ".ivu" : "application/vnd.immervision-ivu",
    ".jad" : "text/vnd.sun.j2me.app-descriptor",
    ".jam" : "application/vnd.jam",
    ".jar" : "application/java-archive",
    ".java" : "text/x-java-source",
    ".jisp" : "application/vnd.jisp",
    ".jlt" : "application/vnd.hp-jlyt",
    ".jnlp" : "application/x-java-jnlp-file",
    ".joda" : "application/vnd.joost.joda-archive",
    ".jpe" : "image/jpeg",
    ".jpeg" : "image/jpeg",
    ".jpg" : "image/jpeg",
    ".jpgm" : "video/jpm",
    ".jpgv" : "video/jpeg",
    ".jpm" : "video/jpm",
    ".js" : "application/javascript",
    ".json" : "application/json",
    ".kar" : "audio/midi",
    ".karbon" : "application/vnd.kde.karbon",
    ".kfo" : "application/vnd.kde.kformula",
    ".kia" : "application/vnd.kidspiration",
    ".kil" : "application/x-killustrator",
    ".kml" : "application/vnd.google-earth.kml+xml",
    ".kmz" : "application/vnd.google-earth.kmz",
    ".kne" : "application/vnd.kinar",
    ".knp" : "application/vnd.kinar",
    ".kon" : "application/vnd.kde.kontour",
    ".kpr" : "application/vnd.kde.kpresenter",
    ".kpt" : "application/vnd.kde.kpresenter",
    ".ksh" : "text/plain",
    ".ksp" : "application/vnd.kde.kspread",
    ".ktr" : "application/vnd.kahootz",
    ".ktz" : "application/vnd.kahootz",
    ".kwd" : "application/vnd.kde.kword",
    ".kwt" : "application/vnd.kde.kword",
    ".latex" : "application/x-latex",
    ".lbd" : "application/vnd.llamagraphics.life-balance.desktop",
    ".lbe" : "application/vnd.llamagraphics.life-balance.exchange+xml",
    ".les" : "application/vnd.hhe.lesson-player",
    ".lha" : "application/octet-stream",
    ".link66" : "application/vnd.route66.link66+xml",
    ".list" : "text/plain",
    ".list3820" : "application/vnd.ibm.modcap",
    ".listafp" : "application/vnd.ibm.modcap",
    ".log" : "text/plain",
    ".lostxml" : "application/lost+xml",
    ".lrf" : "application/octet-stream",
    ".lrm" : "application/vnd.ms-lrm",
    ".ltf" : "application/vnd.frogans.ltf",
    ".lvp" : "audio/vnd.lucent.voice",
    ".lwp" : "application/vnd.lotus-wordpro",
    ".lzh" : "application/octet-stream",
    ".m13" : "application/x-msmediaview",
    ".m14" : "application/x-msmediaview",
    ".m1v" : "video/mpeg",
    ".m2a" : "audio/mpeg",
    ".m2v" : "video/mpeg",
    ".m3a" : "audio/mpeg",
    ".m3u" : "audio/x-mpegurl",
    ".m4u" : "video/vnd.mpegurl",
    ".m4v" : "video/x-m4v",
    ".ma" : "application/mathematica",
    ".mag" : "application/vnd.ecowin.chart",
    ".maker" : "application/vnd.framemaker",
    ".man" : "text/troff",
    ".mathml" : "application/mathml+xml",
    ".mb" : "application/mathematica",
    ".mbk" : "application/vnd.mobius.mbk",
    ".mbox" : "application/mbox",
    ".mc1" : "application/vnd.medcalcdata",
    ".mcd" : "application/vnd.mcd",
    ".mcurl" : "text/vnd.curl.mcurl",
    ".mdb" : "application/x-msaccess",
    ".mdi" : "image/vnd.ms-modi",
    ".me" : "text/troff",
    ".mesh" : "model/mesh",
    ".mfm" : "application/vnd.mfmp",
    ".mgz" : "application/vnd.proteus.magazine",
    ".mht" : "message/rfc822",
    ".mhtml" : "message/rfc822",
    ".mid" : "audio/midi",
    ".midi" : "audio/midi",
    ".mif" : "application/vnd.mif",
    ".mime" : "message/rfc822",
    ".mj2" : "video/mj2",
    ".mjp2" : "video/mj2",
    ".mlp" : "application/vnd.dolby.mlp",
    ".mmd" : "application/vnd.chipnuts.karaoke-mmd",
    ".mmf" : "application/vnd.smaf",
    ".mmr" : "image/vnd.fujixerox.edmics-mmr",
    ".mny" : "application/x-msmoney",
    ".mobi" : "application/x-mobipocket-ebook",
    ".mov" : "video/quicktime",
    ".movie" : "video/x-sgi-movie",
    ".mp2" : "audio/mpeg",
    ".mp2a" : "audio/mpeg",
    ".mp3" : "audio/mpeg",
    ".mp4" : "video/mp4",
    ".mp4a" : "audio/mp4",
    ".mp4s" : "application/mp4",
    ".mp4v" : "video/mp4",
    ".mpa" : "video/mpeg",
    ".mpc" : "application/vnd.mophun.certificate",
    ".mpe" : "video/mpeg",
    ".mpeg" : "video/mpeg",
    ".mpg" : "video/mpeg",
    ".mpg4" : "video/mp4",
    ".mpga" : "audio/mpeg",
    ".mpkg" : "application/vnd.apple.installer+xml",
    ".mpm" : "application/vnd.blueice.multipass",
    ".mpn" : "application/vnd.mophun.application",
    ".mpp" : "application/vnd.ms-project",
    ".mpt" : "application/vnd.ms-project",
    ".mpy" : "application/vnd.ibm.minipay",
    ".mqy" : "application/vnd.mobius.mqy",
    ".mrc" : "application/marc",
    ".ms" : "text/troff",
    ".mscml" : "application/mediaservercontrol+xml",
    ".mseed" : "application/vnd.fdsn.mseed",
    ".mseq" : "application/vnd.mseq",
    ".msf" : "application/vnd.epson.msf",
    ".msh" : "model/mesh",
    ".msi" : "application/x-msdownload",
    ".msl" : "application/vnd.mobius.msl",
    ".msty" : "application/vnd.muvee.style",
    ".mts" : "model/vnd.mts",
    ".mus" : "application/vnd.musician",
    ".musicxml" : "application/vnd.recordare.musicxml+xml",
    ".mvb" : "application/x-msmediaview",
    ".mwf" : "application/vnd.mfer",
    ".mxf" : "application/mxf",
    ".mxl" : "application/vnd.recordare.musicxml",
    ".mxml" : "application/xv+xml",
    ".mxs" : "application/vnd.triscape.mxs",
    ".mxu" : "video/vnd.mpegurl",
    ".n-gage" : "application/vnd.nokia.n-gage.symbian.install",
    ".nb" : "application/mathematica",
    ".nc" : "application/x-netcdf",
    ".ncx" : "application/x-dtbncx+xml",
    ".ngdat" : "application/vnd.nokia.n-gage.data",
    ".nlu" : "application/vnd.neurolanguage.nlu",
    ".nml" : "application/vnd.enliven",
    ".nnd" : "application/vnd.noblenet-directory",
    ".nns" : "application/vnd.noblenet-sealer",
    ".nnw" : "application/vnd.noblenet-web",
    ".npx" : "image/vnd.net-fpx",
    ".nsf" : "application/vnd.lotus-notes",
    ".nws" : "message/rfc822",
    ".o" : "application/octet-stream",
    ".oa2" : "application/vnd.fujitsu.oasys2",
    ".oa3" : "application/vnd.fujitsu.oasys3",
    ".oas" : "application/vnd.fujitsu.oasys",
    ".obd" : "application/x-msbinder",
    ".obj" : "application/octet-stream",
    ".oda" : "application/oda",
    ".odb" : "application/vnd.oasis.opendocument.database",
    ".odc" : "application/vnd.oasis.opendocument.chart",
    ".odf" : "application/vnd.oasis.opendocument.formula",
    ".odft" : "application/vnd.oasis.opendocument.formula-template",
    ".odg" : "application/vnd.oasis.opendocument.graphics",
    ".odi" : "application/vnd.oasis.opendocument.image",
    ".odp" : "application/vnd.oasis.opendocument.presentation",
    ".ods" : "application/vnd.oasis.opendocument.spreadsheet",
    ".odt" : "application/vnd.oasis.opendocument.text",
    ".oga" : "audio/ogg",
    ".ogg" : "audio/ogg",
    ".ogv" : "video/ogg",
    ".ogx" : "application/ogg",
    ".onepkg" : "application/onenote",
    ".onetmp" : "application/onenote",
    ".onetoc" : "application/onenote",
    ".onetoc2" : "application/onenote",
    ".opf" : "application/oebps-package+xml",
    ".oprc" : "application/vnd.palm",
    ".org" : "application/vnd.lotus-organizer",
    ".osf" : "application/vnd.yamaha.openscoreformat",
    ".osfpvg" : "application/vnd.yamaha.openscoreformat.osfpvg+xml",
    ".otc" : "application/vnd.oasis.opendocument.chart-template",
    ".otf" : "application/x-font-otf",
    ".otg" : "application/vnd.oasis.opendocument.graphics-template",
    ".oth" : "application/vnd.oasis.opendocument.text-web",
    ".oti" : "application/vnd.oasis.opendocument.image-template",
    ".otm" : "application/vnd.oasis.opendocument.text-master",
    ".otp" : "application/vnd.oasis.opendocument.presentation-template",
    ".ots" : "application/vnd.oasis.opendocument.spreadsheet-template",
    ".ott" : "application/vnd.oasis.opendocument.text-template",
    ".oxt" : "application/vnd.openofficeorg.extension",
    ".p" : "text/x-pascal",
    ".p10" : "application/pkcs10",
    ".p12" : "application/x-pkcs12",
    ".p7b" : "application/x-pkcs7-certificates",
    ".p7c" : "application/pkcs7-mime",
    ".p7m" : "application/pkcs7-mime",
    ".p7r" : "application/x-pkcs7-certreqresp",
    ".p7s" : "application/pkcs7-signature",
    ".pas" : "text/x-pascal",
    ".pbd" : "application/vnd.powerbuilder6",
    ".pbm" : "image/x-portable-bitmap",
    ".pcf" : "application/x-font-pcf",
    ".pcl" : "application/vnd.hp-pcl",
    ".pclxl" : "application/vnd.hp-pclxl",
    ".pct" : "image/x-pict",
    ".pcurl" : "application/vnd.curl.pcurl",
    ".pcx" : "image/x-pcx",
    ".pdb" : "application/vnd.palm",
    ".pdf" : "application/pdf",
    ".pfa" : "application/x-font-type1",
    ".pfb" : "application/x-font-type1",
    ".pfm" : "application/x-font-type1",
    ".pfr" : "application/font-tdpfr",
    ".pfx" : "application/x-pkcs12",
    ".pgm" : "image/x-portable-graymap",
    ".pgn" : "application/x-chess-pgn",
    ".pgp" : "application/pgp-encrypted",
    ".pic" : "image/x-pict",
    ".pkg" : "application/octet-stream",
    ".pki" : "application/pkixcmp",
    ".pkipath" : "application/pkix-pkipath",
    ".pl" : "text/plain",
    ".plb" : "application/vnd.3gpp.pic-bw-large",
    ".plc" : "application/vnd.mobius.plc",
    ".plf" : "application/vnd.pocketlearn",
    ".pls" : "application/pls+xml",
    ".pml" : "application/vnd.ctc-posml",
    ".png" : "image/png",
    ".pnm" : "image/x-portable-anymap",
    ".portpkg" : "application/vnd.macports.portpkg",
    ".pot" : "application/vnd.ms-powerpoint",
    ".potm" : "application/vnd.ms-powerpoint.template.macroenabled.12",
    ".potx" : "application/vnd.openxmlformats-officedocument.presentationml.template",
    ".ppa" : "application/vnd.ms-powerpoint",
    ".ppam" : "application/vnd.ms-powerpoint.addin.macroenabled.12",
    ".ppd" : "application/vnd.cups-ppd",
    ".ppm" : "image/x-portable-pixmap",
    ".pps" : "application/vnd.ms-powerpoint",
    ".ppsm" : "application/vnd.ms-powerpoint.slideshow.macroenabled.12",
    ".ppsx" : "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
    ".ppt" : "application/vnd.ms-powerpoint",
    ".pptm" : "application/vnd.ms-powerpoint.presentation.macroenabled.12",
    ".pptx" : "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ".pqa" : "application/vnd.palm",
    ".prc" : "application/x-mobipocket-ebook",
    ".pre" : "application/vnd.lotus-freelance",
    ".prf" : "application/pics-rules",
    ".ps" : "application/postscript",
    ".psb" : "application/vnd.3gpp.pic-bw-small",
    ".psd" : "image/vnd.adobe.photoshop",
    ".psf" : "application/x-font-linux-psf",
    ".ptid" : "application/vnd.pvi.ptid1",
    ".pub" : "application/x-mspublisher",
    ".pvb" : "application/vnd.3gpp.pic-bw-var",
    ".pwn" : "application/vnd.3m.post-it-notes",
    ".pwz" : "application/vnd.ms-powerpoint",
    ".py" : "text/x-python",
    ".pya" : "audio/vnd.ms-playready.media.pya",
    ".pyc" : "application/x-python-code",
    ".pyo" : "application/x-python-code",
    ".pyv" : "video/vnd.ms-playready.media.pyv",
    ".qam" : "application/vnd.epson.quickanime",
    ".qbo" : "application/vnd.intu.qbo",
    ".qfx" : "application/vnd.intu.qfx",
    ".qps" : "application/vnd.publishare-delta-tree",
    ".qt" : "video/quicktime",
    ".qwd" : "application/vnd.quark.quarkxpress",
    ".qwt" : "application/vnd.quark.quarkxpress",
    ".qxb" : "application/vnd.quark.quarkxpress",
    ".qxd" : "application/vnd.quark.quarkxpress",
    ".qxl" : "application/vnd.quark.quarkxpress",
    ".qxt" : "application/vnd.quark.quarkxpress",
    ".ra" : "audio/x-pn-realaudio",
    ".ram" : "audio/x-pn-realaudio",
    ".rar" : "application/x-rar-compressed",
    ".ras" : "image/x-cmu-raster",
    ".rcprofile" : "application/vnd.ipunplugged.rcprofile",
    ".rdf" : "application/rdf+xml",
    ".rdz" : "application/vnd.data-vision.rdz",
    ".rep" : "application/vnd.businessobjects",
    ".res" : "application/x-dtbresource+xml",
    ".rgb" : "image/x-rgb",
    ".rif" : "application/reginfo+xml",
    ".rl" : "application/resource-lists+xml",
    ".rlc" : "image/vnd.fujixerox.edmics-rlc",
    ".rld" : "application/resource-lists-diff+xml",
    ".rm" : "application/vnd.rn-realmedia",
    ".rmi" : "audio/midi",
    ".rmp" : "audio/x-pn-realaudio-plugin",
    ".rms" : "application/vnd.jcp.javame.midlet-rms",
    ".rnc" : "application/relax-ng-compact-syntax",
    ".roff" : "text/troff",
    ".rpm" : "application/x-rpm",
    ".rpss" : "application/vnd.nokia.radio-presets",
    ".rpst" : "application/vnd.nokia.radio-preset",
    ".rq" : "application/sparql-query",
    ".rs" : "application/rls-services+xml",
    ".rsd" : "application/rsd+xml",
    ".rss" : "application/rss+xml",
    ".rtf" : "application/rtf",
    ".rtx" : "text/richtext",
    ".s" : "text/x-asm",
    ".saf" : "application/vnd.yamaha.smaf-audio",
    ".sbml" : "application/sbml+xml",
    ".sc" : "application/vnd.ibm.secure-container",
    ".scd" : "application/x-msschedule",
    ".scm" : "application/vnd.lotus-screencam",
    ".scq" : "application/scvp-cv-request",
    ".scs" : "application/scvp-cv-response",
    ".scurl" : "text/vnd.curl.scurl",
    ".sda" : "application/vnd.stardivision.draw",
    ".sdc" : "application/vnd.stardivision.calc",
    ".sdd" : "application/vnd.stardivision.impress",
    ".sdkd" : "application/vnd.solent.sdkm+xml",
    ".sdkm" : "application/vnd.solent.sdkm+xml",
    ".sdp" : "application/sdp",
    ".sdw" : "application/vnd.stardivision.writer",
    ".see" : "application/vnd.seemail",
    ".seed" : "application/vnd.fdsn.seed",
    ".sema" : "application/vnd.sema",
    ".semd" : "application/vnd.semd",
    ".semf" : "application/vnd.semf",
    ".ser" : "application/java-serialized-object",
    ".setpay" : "application/set-payment-initiation",
    ".setreg" : "application/set-registration-initiation",
    ".sfd-hdstx" : "application/vnd.hydrostatix.sof-data",
    ".sfs" : "application/vnd.spotfire.sfs",
    ".sgl" : "application/vnd.stardivision.writer-global",
    ".sgm" : "text/sgml",
    ".sgml" : "text/sgml",
    ".sh" : "application/x-sh",
    ".shar" : "application/x-shar",
    ".shf" : "application/shf+xml",
    ".si" : "text/vnd.wap.si",
    ".sic" : "application/vnd.wap.sic",
    ".sig" : "application/pgp-signature",
    ".silo" : "model/mesh",
    ".sis" : "application/vnd.symbian.install",
    ".sisx" : "application/vnd.symbian.install",
    ".sit" : "application/x-stuffit",
    ".sitx" : "application/x-stuffitx",
    ".skd" : "application/vnd.koan",
    ".skm" : "application/vnd.koan",
    ".skp" : "application/vnd.koan",
    ".skt" : "application/vnd.koan",
    ".sl" : "text/vnd.wap.sl",
    ".slc" : "application/vnd.wap.slc",
    ".sldm" : "application/vnd.ms-powerpoint.slide.macroenabled.12",
    ".sldx" : "application/vnd.openxmlformats-officedocument.presentationml.slide",
    ".slt" : "application/vnd.epson.salt",
    ".smf" : "application/vnd.stardivision.math",
    ".smi" : "application/smil+xml",
    ".smil" : "application/smil+xml",
    ".snd" : "audio/basic",
    ".snf" : "application/x-font-snf",
    ".so" : "application/octet-stream",
    ".spc" : "application/x-pkcs7-certificates",
    ".spf" : "application/vnd.yamaha.smaf-phrase",
    ".spl" : "application/x-futuresplash",
    ".spot" : "text/vnd.in3d.spot",
    ".spp" : "application/scvp-vp-response",
    ".spq" : "application/scvp-vp-request",
    ".spx" : "audio/ogg",
    ".src" : "application/x-wais-source",
    ".srx" : "application/sparql-results+xml",
    ".sse" : "application/vnd.kodak-descriptor",
    ".ssf" : "application/vnd.epson.ssf",
    ".ssml" : "application/ssml+xml",
    ".stc" : "application/vnd.sun.xml.calc.template",
    ".std" : "application/vnd.sun.xml.draw.template",
    ".stf" : "application/vnd.wt.stf",
    ".sti" : "application/vnd.sun.xml.impress.template",
    ".stk" : "application/hyperstudio",
    ".stl" : "application/vnd.ms-pki.stl",
    ".str" : "application/vnd.pg.format",
    ".stw" : "application/vnd.sun.xml.writer.template",
    ".sus" : "application/vnd.sus-calendar",
    ".susp" : "application/vnd.sus-calendar",
    ".sv4cpio" : "application/x-sv4cpio",
    ".sv4crc" : "application/x-sv4crc",
    ".svd" : "application/vnd.svd",
    ".svg" : "image/svg+xml",
    ".svgz" : "image/svg+xml",
    ".swa" : "application/x-director",
    ".swf" : "application/x-shockwave-flash",
    ".swi" : "application/vnd.arastra.swi",
    ".sxc" : "application/vnd.sun.xml.calc",
    ".sxd" : "application/vnd.sun.xml.draw",
    ".sxg" : "application/vnd.sun.xml.writer.global",
    ".sxi" : "application/vnd.sun.xml.impress",
    ".sxm" : "application/vnd.sun.xml.math",
    ".sxw" : "application/vnd.sun.xml.writer",
    ".t" : "text/troff",
    ".tao" : "application/vnd.tao.intent-module-archive",
    ".tar" : "application/x-tar",
    ".tcap" : "application/vnd.3gpp2.tcap",
    ".tcl" : "application/x-tcl",
    ".teacher" : "application/vnd.smart.teacher",
    ".tex" : "application/x-tex",
    ".texi" : "application/x-texinfo",
    ".texinfo" : "application/x-texinfo",
    ".text" : "text/plain",
    ".tfm" : "application/x-tex-tfm",
    ".tgz" : "application/x-gzip",
    ".tif" : "image/tiff",
    ".tiff" : "image/tiff",
    ".tmo" : "application/vnd.tmobile-livetv",
    ".torrent" : "application/x-bittorrent",
    ".tpl" : "application/vnd.groove-tool-template",
    ".tpt" : "application/vnd.trid.tpt",
    ".tr" : "text/troff",
    ".tra" : "application/vnd.trueapp",
    ".trm" : "application/x-msterminal",
    ".tsv" : "text/tab-separated-values",
    ".ttc" : "application/x-font-ttf",
    ".ttf" : "application/x-font-ttf",
    ".twd" : "application/vnd.simtech-mindmapper",
    ".twds" : "application/vnd.simtech-mindmapper",
    ".txd" : "application/vnd.genomatix.tuxedo",
    ".txf" : "application/vnd.mobius.txf",
    ".txt" : "text/plain",
    ".u32" : "application/x-authorware-bin",
    ".udeb" : "application/x-debian-package",
    ".ufd" : "application/vnd.ufdl",
    ".ufdl" : "application/vnd.ufdl",
    ".umj" : "application/vnd.umajin",
    ".unityweb" : "application/vnd.unity",
    ".uoml" : "application/vnd.uoml+xml",
    ".uri" : "text/uri-list",
    ".uris" : "text/uri-list",
    ".urls" : "text/uri-list",
    ".ustar" : "application/x-ustar",
    ".utz" : "application/vnd.uiq.theme",
    ".uu" : "text/x-uuencode",
    ".vcd" : "application/x-cdlink",
    ".vcf" : "text/x-vcard",
    ".vcg" : "application/vnd.groove-vcard",
    ".vcs" : "text/x-vcalendar",
    ".vcx" : "application/vnd.vcx",
    ".vis" : "application/vnd.visionary",
    ".viv" : "video/vnd.vivo",
    ".vor" : "application/vnd.stardivision.writer",
    ".vox" : "application/x-authorware-bin",
    ".vrml" : "model/vrml",
    ".vsd" : "application/vnd.visio",
    ".vsf" : "application/vnd.vsf",
    ".vss" : "application/vnd.visio",
    ".vst" : "application/vnd.visio",
    ".vsw" : "application/vnd.visio",
    ".vtu" : "model/vnd.vtu",
    ".vxml" : "application/voicexml+xml",
    ".w3d" : "application/x-director",
    ".wad" : "application/x-doom",
    ".wav" : "audio/x-wav",
    ".wax" : "audio/x-ms-wax",
    ".wbmp" : "image/vnd.wap.wbmp",
    ".wbs" : "application/vnd.criticaltools.wbs+xml",
    ".wbxml" : "application/vnd.wap.wbxml",
    ".wcm" : "application/vnd.ms-works",
    ".wdb" : "application/vnd.ms-works",
    ".wiz" : "application/msword",
    ".wks" : "application/vnd.ms-works",
    ".wm" : "video/x-ms-wm",
    ".wma" : "audio/x-ms-wma",
    ".wmd" : "application/x-ms-wmd",
    ".wmf" : "application/x-msmetafile",
    ".wml" : "text/vnd.wap.wml",
    ".wmlc" : "application/vnd.wap.wmlc",
    ".wmls" : "text/vnd.wap.wmlscript",
    ".wmlsc" : "application/vnd.wap.wmlscriptc",
    ".wmv" : "video/x-ms-wmv",
    ".wmx" : "video/x-ms-wmx",
    ".wmz" : "application/x-ms-wmz",
    ".wpd" : "application/vnd.wordperfect",
    ".wpl" : "application/vnd.ms-wpl",
    ".wps" : "application/vnd.ms-works",
    ".wqd" : "application/vnd.wqd",
    ".wri" : "application/x-mswrite",
    ".wrl" : "model/vrml",
    ".wsdl" : "application/wsdl+xml",
    ".wspolicy" : "application/wspolicy+xml",
    ".wtb" : "application/vnd.webturbo",
    ".wvx" : "video/x-ms-wvx",
    ".x32" : "application/x-authorware-bin",
    ".x3d" : "application/vnd.hzn-3d-crossword",
    ".xap" : "application/x-silverlight-app",
    ".xar" : "application/vnd.xara",
    ".xbap" : "application/x-ms-xbap",
    ".xbd" : "application/vnd.fujixerox.docuworks.binder",
    ".xbm" : "image/x-xbitmap",
    ".xdm" : "application/vnd.syncml.dm+xml",
    ".xdp" : "application/vnd.adobe.xdp+xml",
    ".xdw" : "application/vnd.fujixerox.docuworks",
    ".xenc" : "application/xenc+xml",
    ".xer" : "application/patch-ops-error+xml",
    ".xfdf" : "application/vnd.adobe.xfdf",
    ".xfdl" : "application/vnd.xfdl",
    ".xht" : "application/xhtml+xml",
    ".xhtml" : "application/xhtml+xml",
    ".xhvml" : "application/xv+xml",
    ".xif" : "image/vnd.xiff",
    ".xla" : "application/vnd.ms-excel",
    ".xlam" : "application/vnd.ms-excel.addin.macroenabled.12",
    ".xlb" : "application/vnd.ms-excel",
    ".xlc" : "application/vnd.ms-excel",
    ".xlm" : "application/vnd.ms-excel",
    ".xls" : "application/vnd.ms-excel",
    ".xlsb" : "application/vnd.ms-excel.sheet.binary.macroenabled.12",
    ".xlsm" : "application/vnd.ms-excel.sheet.macroenabled.12",
    ".xlsx" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ".xlt" : "application/vnd.ms-excel",
    ".xltm" : "application/vnd.ms-excel.template.macroenabled.12",
    ".xltx" : "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
    ".xlw" : "application/vnd.ms-excel",
    ".xml" : "application/xml",
    ".xo" : "application/vnd.olpc-sugar",
    ".xop" : "application/xop+xml",
    ".xpdl" : "application/xml",
    ".xpi" : "application/x-xpinstall",
    ".xpm" : "image/x-xpixmap",
    ".xpr" : "application/vnd.is-xpr",
    ".xps" : "application/vnd.ms-xpsdocument",
    ".xpw" : "application/vnd.intercon.formnet",
    ".xpx" : "application/vnd.intercon.formnet",
    ".xsl" : "application/xml",
    ".xslt" : "application/xslt+xml",
    ".xsm" : "application/vnd.syncml+xml",
    ".xspf" : "application/xspf+xml",
    ".xul" : "application/vnd.mozilla.xul+xml",
    ".xvm" : "application/xv+xml",
    ".xvml" : "application/xv+xml",
    ".xwd" : "image/x-xwindowdump",
    ".xyz" : "chemical/x-xyz",
    ".zaz" : "application/vnd.zzazz.deck+xml",
    ".zip" : "application/zip",
    ".zir" : "application/vnd.zul",
    ".zirz" : "application/vnd.zul",
    ".zmm" : "application/vnd.handheld-entertainment+xml"
  }

  constructor() {}

  getMagicBytesData(): MagicByte[] {
    return this.magic_bytes_data;
  }

  getFileExtensionMimeTypeMap() {
    return this.fileExtensionMimeTypeMap;
  }
}
